#!/bin/sh
set -e

export PGPASSWORD="${POSTGRES_PASSWORD}"

poll_for_db() {
  psql -h$POSTGRES_HOST -p$POSTGRES_PORT -U$POSTGRES_USER -d$POSTGRES_DATABASE -w -c'\c' | grep -q 'You are now connected to database'
}

while ! poll_for_db ; do
  sleep 1
done

rake db:create db:migrate
exec bundle exec rackup --quiet --host 0.0.0.0
